<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TR13IT0HI1KA2010" failures="0" tests="1" name="RestAssured4.JSON_Array2" time="1.432" errors="1" timestamp="2022-08-04T21:51:43 IST" skipped="0">
  <testcase classname="RestAssured4.JSON_Array2" name="JsonPathUsage" time="1.432">
    <error message="org/codehaus/groovy/runtime/memoize/EvictableCache" type="java.lang.NoClassDefFoundError">
      <![CDATA[java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/memoize/EvictableCache
at org.apache.groovy.json.internal.CharBuf.addInt(CharBuf.java:138)
at groovy.json.DefaultJsonGenerator.writeNumber(DefaultJsonGenerator.java:127)
at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:194)
at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:381)
at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:369)
at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:200)
at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
at groovy.json.DefaultJsonGenerator.toJson(DefaultJsonGenerator.java:98)
at groovy.json.JsonBuilder.toString(JsonBuilder.java:376)
at io.restassured.path.json.JsonPath.objectToString(JsonPath.java:1059)
at io.restassured.path.json.JsonPath.getList(JsonPath.java:398)
at RestAssured4.JSON_Array2.JsonPathUsage(JSON_Array2.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.memoize.EvictableCache
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 40 more
]]>
    </error>
  </testcase> <!-- JsonPathUsage -->
  <system-out/>
</testsuite> <!-- RestAssured4.JSON_Array2 -->
